import { Metadata } from "next";

export default function About() {
    return <h1>About us</h1>
}
export const metadata: Metadata = {
    title: "About us",
    description: "Generated by create next app",
  };
