import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const navLink = [
  {
    name: "Login",
    href: "./login",
  },
  {
    name: "Register",
    href: "./register",
  },
  {
    name: "Profile",
    href: "./profile",
  },
];

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "BitStorm",
    template: "%s | BitStorm",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1
            style={{
              backgroundColor: "#E0A75E",
              padding: "50px",
            }}
          >
            Header here
            <ul>
              {navLink.map((link) => (
                <li key={link.name}>
                  <Link href={link.href}>{link.name}</Link>
                </li>
              ))}
            </ul>
          </h1>
        </header>
        <main style={{ backgroundColor: "#973131", padding: "100px" }}>
          {children}
        </main>
        <footer>
          <h1
            style={{
              backgroundColor: "#E0A75E",
              padding: "50px",
            }}
          >
            Foooter here
          </h1>
        </footer>
      </body>
    </html>
  );
}
