import { Metadata } from "next";
import Image from "next/image";
export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "BitStorm",
    template: "%s | BitStorm",
  },
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
        <h1>Welcom home!</h1>
    </main>
  );
}
